### ISSUE TITLE
key.toggle problems

### ISSUE THREAD

**Issue by nickehallgren** [msanders/autopy#65]
Hi,

I installed autopy on debian 7 using your instructions (compile from git)) and the Hello World example works but when I try to send CTRL + 1 I get an error, this is my code:
```
import autopy, time

def key_demo():
  autopy.key.toggle('1', True, autopy.key.MOD_CONTROL)
  time.sleep(2)
  autopy.key.toggle('1', False, autopy.key.MOD_CONTROL)  

def hello_there_world():
    autopy.alert.alert("Hello, world")

hello_there_world()
key_demo()
```
and the result is this:

Traceback (most recent call last):
  File "autopy_demo.py", line 12, in <module>
    key_demo()
  File "autopy_demo.py", line 4, in key_demo
    autopy.key.toggle('1', True, autopy.key.MOD_CONTROL)
TypeError: argument 1 must be integer<H> or char, not str

I'm pretty sure I have used the same code in another project so can this be that some library or something is missing?

**Comment by carlpett** [comment]
I have this problem as well. Somewhat surprisingly, it works if I cast to unicode first, which in your case would be 

    def key_demo():
      autopy.key.toggle(u'1', True, autopy.key.MOD_CONTROL)
      time.sleep(2)
      autopy.key.toggle(u'1', False, autopy.key.MOD_CONTROL)  

I looked into the source (`autopy-key-module.c`, code excerpt below), and I'm guessing there might be a problem with `PyUnicode_Check`. I couldn't locate the source for that one, though (checked python source)

	if (PyNumber_Check(key)) { /* Check for key code */
		MMKeyCode code;
		if (!MMKeyCodeFromPyInt(key, &code)) return NULL;
		toggleKeyCode(code, downBool == Py_True, flags);
	} else if (PyUnicode_Check(key)) { /* Check for single-character string */
		char c;
		if (!charFromPyString(key, &c)) return NULL;
		toggleKey(c, downBool == Py_True, flags);
	} else {
		return Py_SetArgConvertErr("integer<H> or char", 1, key);
	}

**Comment by raga70** [comment]
how i can togle enter key

**Comment by flufy3d** [comment]
Got an idea from #65. Cast numbers to long and it works.

key.toggle(long(key.K_DELETE), True)

**Comment by msanders** [comment]
This should be fixed now in the [latest version](https://github.com/autopilot-rs/autopy) of AutoPy.
