### ISSUE TITLE
Can't install from pip "Missing parenthesis in call to 'print'"

### ISSUE THREAD

**Issue by spikespaz** [msanders/autopy#89]
Did you forget Python3 print syntax?

```
> pip install autopy
Collecting autopy
  Using cached autopy-0.51.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\spike\AppData\Local\Temp\pip-build-muwkyl8h\autopy\setup.py", line 50
        print 'Updating __init__.py'
                                   ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\spike\AppData\Local\Temp\pip-build-muwkyl8h\autopy\
```

**Comment by imfatant** [comment]
Yeah I have this issue. Is there a quick fix?

**Comment by Zeratec** [comment]
Parentheses are present in the script... but the error is always present.. Do you have a solution ?

**Comment by msanders** [comment]
This is be fixed now in the [latest version](https://github.com/autopilot-rs/autopy) of AutoPy.
